// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateService(arg1:string):Promise<void>;

export function AddFolder(arg1:string,arg2:string):Promise<string>;

export function AddService(arg1:string,arg2:string):Promise<string>;

export function ChangeCredentialValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ChangeResourceName(arg1:string,arg2:number,arg3:string):Promise<string>;

export function ChangeResourceSetting(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function ClickOpenWorkspace(arg1:string):Promise<string>;

export function CloseContextMenuAddResource(arg1:string):Promise<string>;

export function CloseContextMenuAddService(arg1:string):Promise<string>;

export function CloseContextMenuResource(arg1:string):Promise<string>;

export function CloseContextMenuService(arg1:string):Promise<string>;

export function CloseDialog(arg1:string):Promise<string>;

export function CloseDropdown(arg1:string):Promise<string>;

export function CloseResourceSetting(arg1:string):Promise<string>;

export function CloseService(arg1:string):Promise<string>;

export function DeactivateService(arg1:string):Promise<void>;

export function ExpandResource(arg1:string,arg2:number):Promise<string>;

export function ExportService(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HandleActivateCredentials(arg1:string):Promise<string>;

export function HandleActivateProvider(arg1:string,arg2:string):Promise<string>;

export function HandleContextMenuAddResource(arg1:string,arg2:string):Promise<string>;

export function HandleContextMenuAddService(arg1:string,arg2:string):Promise<string>;

export function HandleContextMenuResource(arg1:string,arg2:string,arg3:string):Promise<string>;

export function HandleContextMenuService(arg1:string,arg2:string,arg3:string):Promise<string>;

export function HandleDeactivateCredentials(arg1:string):Promise<string>;

export function HandleDeleteCredentials(arg1:string):Promise<string>;

export function HandleDropdown(arg1:string,arg2:string):Promise<string>;

export function HandleDropdownSize(arg1:string,arg2:string):Promise<string>;

export function HandleDropdownTheme(arg1:string,arg2:string):Promise<string>;

export function ImportService(arg1:string,arg2:string):Promise<string>;

export function LoadStatus(arg1:string):Promise<string>;

export function NavigateChild(arg1:string,arg2:string):Promise<string>;

export function NavigateParent(arg1:string):Promise<string>;

export function NewState():Promise<string>;

export function OpenContextMenuAddResource(arg1:string,arg2:number,arg3:number):Promise<string>;

export function OpenContextMenuAddService(arg1:string,arg2:number,arg3:number):Promise<string>;

export function OpenContextMenuResource(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function OpenContextMenuService(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function OpenDropdown(arg1:string,arg2:number,arg3:string):Promise<string>;

export function OpenDropdownSize(arg1:string):Promise<string>;

export function OpenDropdownTheme(arg1:string):Promise<string>;

export function OpenMenuService(arg1:string):Promise<string>;

export function OpenResourceSetting(arg1:string,arg2:number,arg3:string):Promise<string>;

export function OpenService(arg1:string):Promise<string>;

export function OpenSettings(arg1:string):Promise<string>;

export function OpenWorkspace(arg1:string):Promise<string>;

export function RemoveService(arg1:string):Promise<void>;

export function ReorderResources(arg1:string,arg2:string):Promise<string>;

export function SaveFiles(arg1:string):Promise<string>;

export function ViewService(arg1:string,arg2:string):Promise<string>;

export function ViewWorkspaceChild(arg1:string,arg2:string):Promise<string>;

export function ViewWorkspaceParent(arg1:string):Promise<string>;
