// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateService(arg1) {
  return window['go']['main']['App']['ActivateService'](arg1);
}

export function AddFolder(arg1, arg2) {
  return window['go']['main']['App']['AddFolder'](arg1, arg2);
}

export function AddService(arg1, arg2) {
  return window['go']['main']['App']['AddService'](arg1, arg2);
}

export function ChangeCredentialValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChangeCredentialValue'](arg1, arg2, arg3, arg4);
}

export function ChangeResourceName(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeResourceName'](arg1, arg2, arg3);
}

export function ChangeResourceSetting(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChangeResourceSetting'](arg1, arg2, arg3, arg4);
}

export function ClickOpenWorkspace(arg1) {
  return window['go']['main']['App']['ClickOpenWorkspace'](arg1);
}

export function CloseContextMenuAddResource(arg1) {
  return window['go']['main']['App']['CloseContextMenuAddResource'](arg1);
}

export function CloseContextMenuAddService(arg1) {
  return window['go']['main']['App']['CloseContextMenuAddService'](arg1);
}

export function CloseContextMenuResource(arg1) {
  return window['go']['main']['App']['CloseContextMenuResource'](arg1);
}

export function CloseContextMenuService(arg1) {
  return window['go']['main']['App']['CloseContextMenuService'](arg1);
}

export function CloseDialog(arg1) {
  return window['go']['main']['App']['CloseDialog'](arg1);
}

export function CloseDropdown(arg1) {
  return window['go']['main']['App']['CloseDropdown'](arg1);
}

export function CloseResourceSetting(arg1) {
  return window['go']['main']['App']['CloseResourceSetting'](arg1);
}

export function CloseService(arg1) {
  return window['go']['main']['App']['CloseService'](arg1);
}

export function DeactivateService(arg1) {
  return window['go']['main']['App']['DeactivateService'](arg1);
}

export function ExpandResource(arg1, arg2) {
  return window['go']['main']['App']['ExpandResource'](arg1, arg2);
}

export function ExportService(arg1, arg2) {
  return window['go']['main']['App']['ExportService'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleActivateCredentials(arg1) {
  return window['go']['main']['App']['HandleActivateCredentials'](arg1);
}

export function HandleActivateProvider(arg1, arg2) {
  return window['go']['main']['App']['HandleActivateProvider'](arg1, arg2);
}

export function HandleContextMenuAddResource(arg1, arg2) {
  return window['go']['main']['App']['HandleContextMenuAddResource'](arg1, arg2);
}

export function HandleContextMenuAddService(arg1, arg2) {
  return window['go']['main']['App']['HandleContextMenuAddService'](arg1, arg2);
}

export function HandleContextMenuResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleContextMenuResource'](arg1, arg2, arg3);
}

export function HandleContextMenuService(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleContextMenuService'](arg1, arg2, arg3);
}

export function HandleDeactivateCredentials(arg1) {
  return window['go']['main']['App']['HandleDeactivateCredentials'](arg1);
}

export function HandleDeleteCredentials(arg1) {
  return window['go']['main']['App']['HandleDeleteCredentials'](arg1);
}

export function HandleDropdown(arg1, arg2) {
  return window['go']['main']['App']['HandleDropdown'](arg1, arg2);
}

export function HandleDropdownSize(arg1, arg2) {
  return window['go']['main']['App']['HandleDropdownSize'](arg1, arg2);
}

export function HandleDropdownTheme(arg1, arg2) {
  return window['go']['main']['App']['HandleDropdownTheme'](arg1, arg2);
}

export function ImportService(arg1, arg2) {
  return window['go']['main']['App']['ImportService'](arg1, arg2);
}

export function LoadStatus(arg1) {
  return window['go']['main']['App']['LoadStatus'](arg1);
}

export function NavigateChild(arg1, arg2) {
  return window['go']['main']['App']['NavigateChild'](arg1, arg2);
}

export function NavigateParent(arg1) {
  return window['go']['main']['App']['NavigateParent'](arg1);
}

export function NewState() {
  return window['go']['main']['App']['NewState']();
}

export function OpenContextMenuAddResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenContextMenuAddResource'](arg1, arg2, arg3);
}

export function OpenContextMenuAddService(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenContextMenuAddService'](arg1, arg2, arg3);
}

export function OpenContextMenuResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenContextMenuResource'](arg1, arg2, arg3, arg4);
}

export function OpenContextMenuService(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenContextMenuService'](arg1, arg2, arg3, arg4);
}

export function OpenDropdown(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenDropdown'](arg1, arg2, arg3);
}

export function OpenDropdownSize(arg1) {
  return window['go']['main']['App']['OpenDropdownSize'](arg1);
}

export function OpenDropdownTheme(arg1) {
  return window['go']['main']['App']['OpenDropdownTheme'](arg1);
}

export function OpenMenuService(arg1) {
  return window['go']['main']['App']['OpenMenuService'](arg1);
}

export function OpenResourceSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenResourceSetting'](arg1, arg2, arg3);
}

export function OpenService(arg1) {
  return window['go']['main']['App']['OpenService'](arg1);
}

export function OpenSettings(arg1) {
  return window['go']['main']['App']['OpenSettings'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function RemoveService(arg1) {
  return window['go']['main']['App']['RemoveService'](arg1);
}

export function ReorderResources(arg1, arg2) {
  return window['go']['main']['App']['ReorderResources'](arg1, arg2);
}

export function SaveFiles(arg1) {
  return window['go']['main']['App']['SaveFiles'](arg1);
}

export function ViewService(arg1, arg2) {
  return window['go']['main']['App']['ViewService'](arg1, arg2);
}

export function ViewWorkspaceChild(arg1, arg2) {
  return window['go']['main']['App']['ViewWorkspaceChild'](arg1, arg2);
}

export function ViewWorkspaceParent(arg1) {
  return window['go']['main']['App']['ViewWorkspaceParent'](arg1);
}
